pipeline {
    agent {
        dockerfile {
            dir 'm4'
        }
    }
    stages {
        stage('Verify') {
            steps {
                sh'''
                    dotnet --list-sdks
                    dotnet --list-runtimes
                '''
            }
        }
        stage('Smoke Test') {
            steps {
                sh 'docker run jaimesalas/jenkins-pipeline-demos:0.0.1'
            }
        }
    }
}