library identifier: 'jenkins-pipeline-demo-library@main',
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/JaimeSalas/jenkins-pipeline-demo-library'])

pipeline {
    agent any
    stages {
        stage('Audit tools') {
            steps {
                auditTools()
            }
        }
    }
}